export const PERSONAS = [
  {
    id: "carter",
    name: "Carter",
    role: "Chief Technology Officer",
    company: "CTO · Enterprise or digital-native company",
    tags: ["Executive sponsor", "Strategic buyer", "Innovation-driven", "Late-stage"],
    triggers: [
      "Clear alignment between the platform and the org's broader AI/ML strategy",
      "Ability to accelerate ML maturity and drive competitive advantage",
      "A vendor with a credible long-term vision and strong track record",
      "Enterprise-grade security, scalability, and reliability at org-wide scale",
      "A compelling business case he can stand behind in a board conversation",
    ],
    redFlags: [
      "Can't articulate the business value clearly — he won't do that work for you",
      "Concerns about vendor lock-in or long-term strategic fit",
      "No clear path from pilot to enterprise-wide rollout",
      "Too much time required to get C-suite alignment — he has competing priorities",
      "Pitch isn't crisp — he'll disengage fast if it's not strategic",
    ],
    proof: [
      "A strategic narrative, not just a product pitch — show how this fits his technology vision",
      "Enterprise customer references at comparable scale and complexity",
      "Analyst recognition (Gartner, Forrester) or industry validation",
      "A clear path to org-wide adoption with defined milestones and ROI checkpoints",
      "Exec-level relationship and responsiveness from the W&B team",
    ],
    simContext: "You are Carter, CTO of a large enterprise. You get pulled into big deals late — after Diana and Malik have done the legwork. You're not hands-on with the tool but you need to believe in the vendor's vision and the business case. You ask big-picture questions: where is this going, what does this mean for our org in 3 years, can I trust this vendor. You're direct and time-constrained. Keep responses 2-3 sentences.",
    opener: "Diana's team has been evaluating this for a few weeks. Give me the 60-second version of why this is the right call.",
  },
  {
    id: "malik",
    name: "Malik",
    role: "ML Engineer",
    company: "Senior IC / Tech Lead · AI-native or enterprise ML team",
    tags: ["Hands-on evaluator", "Influencer", "Champion", "Productivity-driven"],
    triggers: [
      "Seamless integration with his existing ML stack (PyTorch, TF, HuggingFace, etc.)",
      "Automated experiment tracking with zero extra code or reporting overhead",
      "Fast, iterative workflow — compare runs, visualize results, share with teammates instantly",
      "Model registry and versioning that doesn't slow him down",
      "Strong docs, code samples, and a community he trusts",
    ],
    redFlags: [
      "Steep learning curve or heavy onboarding before getting value",
      "Feels like a reporting tool rather than something that helps him build better models",
      "Poor integration with current frameworks or requires ripping out existing tooling",
      "Perceived high cost compared to open-source alternatives like MLflow",
      "No hands-on trial — forced into a sales process before he can evaluate",
    ],
    proof: [
      "Let him try it himself — a working notebook or Colab demo with his own use case",
      "Code samples and end-to-end demos that match his stack",
      "Peer recommendations from engineers he respects (community, GitHub, Reddit)",
      "Show experiment tracking + model registry + collaboration in one workflow",
      "Customer stories from teams like his — faster iteration, better reproducibility",
    ],
    simContext: "You are Malik, a Senior ML Engineer at a tech company. You are hands-on, technically sharp, and deeply skeptical of tools that add overhead without clear payoff. You evaluate tools yourself — you don't trust sales decks, you trust your own experience. You care about: does this integrate with my stack, does it make me faster, can I share results without extra work. You're friendly but direct. If something sounds like marketing fluff you'll call it out. Keep responses 2-3 sentences.",
    opener: "Hey — can I just try this myself, or do I have to sit through a demo first?",
  },
  {
    id: "diana",
    name: "Diana",
    role: "Director of ML",
    company: "Head / VP of AI·ML · Enterprise or growth-stage company",
    tags: ["Decision maker", "Budget owner", "ROI-focused", "Team productivity"],
    triggers: [
      "A single system of record for all ML experiments, models, and artifacts across the team",
      "Visibility into what her team is working on without chasing them for updates",
      "Clear ROI story: faster model delivery, reduced rework, better collaboration",
      "Enterprise readiness: security, compliance, SSO, audit trails",
      "A vendor that acts like a strategic partner, not just a tool",
    ],
    redFlags: [
      "Sticker shock without a clear ROI framing upfront",
      "No alignment between the platform and her team's ML strategy",
      "Resistance from her ML team — if Malik isn't on board, she won't push it",
      "Governance and compliance questions that can't be answered clearly",
      "Vendor feels like a point solution, not a platform investment",
    ],
    proof: [
      "Case studies from similar orgs showing measurable productivity gains and faster delivery",
      "A clear ROI/TCO narrative she can bring to her CFO or CTO",
      "References from ML leaders at companies she respects",
      "Enterprise security and compliance documentation ready to share with legal/IT",
      "A Customer Success model that makes her look good to her stakeholders",
    ],
    simContext: "You are Diana, Director of ML at a mid-to-large enterprise. You manage a team of ML engineers and own the ML budget. You need both: Malik has to want it, and you have to justify it upward. You're strategic and measured — you ask about ROI, team adoption, and what happens after the contract is signed. Keep responses 2-3 sentences, focused on business impact and team dynamics.",
    opener: "Before we go any further — what does success actually look like 6 months after we sign?",
  },
  {
    id: "paul",
    name: "Paul",
    role: "ML Platform Engineer",
    company: "MLOps / ML Platform team · Enterprise",
    tags: ["Influencer or detractor", "Infrastructure-focused", "Security-first", "OSS-leaning"],
    triggers: [
      "Seamless integration with existing ML infrastructure — no ripping out what's already working",
      "Strong security posture: SSO, RBAC, audit logs, private cloud/on-prem options",
      "Reduces infrastructure management overhead vs. building and maintaining OSS alternatives",
      "Clear API documentation and reliable support SLAs",
      "Scalable architecture that won't break when the ML team doubles in size",
    ],
    redFlags: [
      "Feels like vendor lock-in with no clear exit path",
      "Overlaps with or competes with internal tools his team already built",
      "Poor integration with specific frameworks or deployment targets they rely on",
      "One-size-fits-all approach that ignores specific infra requirements",
      "On-prem requirements add cost and complexity without clear justification",
    ],
    proof: [
      "Detailed architecture diagrams and security documentation he can review himself",
      "Clear integration guides for his specific stack — not generic docs",
      "Proof that the platform scales: customer examples at similar infrastructure complexity",
      "An honest comparison against OSS alternatives (MLflow, DVC) on tradeoffs",
      "Strong support SLAs and a dedicated technical contact post-sale",
    ],
    simContext: "You are Paul, a Staff ML Platform Engineer responsible for the infrastructure Malik's team runs on. You are deeply skeptical of new tools — every new platform creates integration work, migration risk, and ongoing maintenance. You've been burned before by tools that were great for ML engineers but a nightmare for your team to support. You ask hard infrastructure questions: auth model, deployment options, failure modes. You're not hostile but need to be convinced this won't make your life harder. Keep responses 2-3 sentences, technical and specific.",
    opener: "Walk me through the deployment architecture. We're not adopting anything that can't run in our VPC.",
  },
  {
    id: "sonia",
    name: "Sonia",
    role: "AI Developer",
    company: "Senior IC / Tech Lead · AI-native or enterprise AI team",
    tags: ["Weave champion", "Influencer", "Hands-on evaluator", "Speed-driven"],
    triggers: [
      "One line of code to start — no complex setup or ripping out existing tooling",
      "Seamless integration with the LLMs, agent frameworks, and tools she already uses",
      "Ability to evaluate, trace, and iterate on agents end-to-end in one place",
      "Production monitoring and guardrails she can show management for safety and quality",
      "Strong docs, code samples, and a community she trusts",
    ],
    redFlags: [
      "Complex onboarding or heavy setup before she gets value",
      "Tool doesn't integrate with her existing stack (LangChain, OpenAI, Anthropic, DSPy, etc.)",
      "No clear path from experimentation to production monitoring in the same platform",
      "Competitive tools are better known — brand recognition gap creates internal skepticism",
      "Can't demonstrate AI safety or quality metrics to management",
    ],
    proof: [
      "One-line integration demo with her exact stack — she needs to see it work immediately",
      "End-to-end demo: explore, evaluate, iterate, deploy, monitor in one workflow",
      "Peer recommendations from AI developers she respects (GitHub, X, Reddit, conferences)",
      "Customer stories from teams shipping production AI agents faster with Weave",
      "Code samples and notebooks she can run herself before any sales conversation",
    ],
    simContext: "You are Sonia, a Senior AI Developer at a tech company building LLM-powered agents and applications. You are hands-on, move fast, and are deeply skeptical of tools that slow you down or require heavy integration work. You evaluate everything yourself — you don't trust marketing decks, you trust your own experience running evals and traces. You care about: does this integrate with my stack in one line, can I evaluate and monitor my agents end-to-end, and can I show my manager that our AI is safe and improving. You are friendly but direct, and will immediately push back on anything that sounds like overhead. Keep responses 2-3 sentences.",
    opener: "I've got 10 minutes — show me how this works with my existing stack without me having to rewrite anything.",
  },
]

export const STAGES = ["Discovery", "POV", "Security", "Procurement", "Rollout", "Closed won"]
